name: bloom

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v4

    - uses: ros-tooling/setup-ros@v0.7

    - name: install dependencies
      run: |
        apt update
        apt install -y python3-bloom dpkg-dev debhelper

    # https://gist.github.com/awesomebytes/196eab972a94dd8fcdd69adfe3bd1152
    - name: create debian package
      run: |
        bloom-generate rosdebian --ros-distro humble
        fakeroot debian/rules binary
