name: bloom

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04
      volumes:
        - /mnt:/tmp

    steps:
    - run: |
        chmod 777 /tmp
        df -h

    - uses: actions/checkout@v4

    - uses: ros-tooling/setup-ros@v0.7

    - name: install dependencies
      run: |
        apt update
        apt install -y python3-bloom python3-rosdep dpkg-dev debhelper devscripts equivs fakeroot
        rm /etc/ros/rosdep/sources.list.d/20-default.list
        rosdep init
        rosdep update

    # https://gist.github.com/awesomebytes/196eab972a94dd8fcdd69adfe3bd1152
    - name: set up debian package
      run: |
        bloom-generate rosdebian --ros-distro humble
        mk-build-deps
        apt install -y ./ros-*-build-deps*.deb

    - name: check nvcc
      run: |
        which nvcc
        nvcc --version

    - name: build debian package
      run: |
        fakeroot debian/rules binary

    - name: check free space
      if: always()
      run: |
        df -h
