name: colcon

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v4

    - uses: ros-tooling/setup-ros@v0.7

    - name: insall GCC 10
      run: |
        sudo apt install -y g++-10

    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: libtorch
        target-ros2-distro: humble
